# -*- coding: utf-8 -*-
"""Personal Information.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rLvYsFhmThTUXHXTncbPZvVxWAFGw_99
"""

print("Ufaq Fatima")

import ipywidgets as widgets
from IPython.display import display

# Create text input widgets
first_name = widgets.Text(placeholder='Enter your first name')
last_name = widgets.Text(placeholder='Enter your last name')
age = widgets.Text(placeholder='Enter your age')
city = widgets.Text(placeholder='Enter your city')

# Display them
display(first_name, last_name, age, city)

# Button to show results
button = widgets.Button(description="Submit")
output = widgets.Output()

def on_button_clicked(b):
    with output:
        output.clear_output()
        print(f"First name: {first_name.value}")
        print(f"Last name: {last_name.value}")
        print(f"Age: {age.value}")
        print(f"City: {city.value}")

button.on_click(on_button_clicked)
display(button, output)